<?php

namespace WorkshopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
    public function findCustomerBySurname($surname)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM WorkshopBundle:person p WHERE p.surname = :surname')->setParameter('surname', $surname)
            ->getResult();
    }

    public function findAllCustomers()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM WorkshopBundle:person p WHERE p.customer = TRUE')->getResult();
    }

    public function findAllWorkers()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM WorkshopBundle:person p WHERE p.customer = FALSE')->getResult();
    }
}
