<?php

namespace WorkshopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WorkOrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkOrderItemRepository extends EntityRepository
{
}
