workshop:
    resource: "@WorkshopBundle/Controller/"
    type:     annotation
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api:
    resource: "@WorkshopBundle/Controller/ApiController.php"
    prefix: /api/
    type: rest