# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:    
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout: true
            anonymous: true

    access_control:
        - { path: ^/login, allow_if: "not has_role('ROLE_USER')" }
        - { path: ^/register, allow_if: "not has_role('ROLE_USER')" }
        - { path: ^/resetting, allow_if: "not has_role('ROLE_USER')" }
        - { path: ^/mail, allow_if: "has_role('ROLE_USER')" }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/customer, role: ROLE_CUSTOMER }

